// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RESTauranter.Models;
using System;

namespace RESTauranter.Migrations
{
    [DbContext(typeof(RESTContext))]
    [Migration("20180614201548_CreateDataBase")]
    partial class CreateDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("RESTauranter.Models.review", b =>
                {
                    b.Property<int>("reviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("date");

                    b.Property<string>("restaurantname");

                    b.Property<string>("reviewername");

                    b.Property<string>("reviews");

                    b.Property<int>("star");

                    b.HasKey("reviewId");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
