// <auto-generated />
using bankacc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace bankacc.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20180615232228_account5")]
    partial class account5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("bankacc.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.HasKey("AccountId");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("bankacc.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("confirmpass")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("PersonId");

                    b.HasIndex("AccountId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("bankacc.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentBalance");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Deposit");

                    b.Property<int?>("TransactionId1");

                    b.HasKey("TransactionId");

                    b.HasIndex("TransactionId1");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("bankacc.Models.Person", b =>
                {
                    b.HasOne("bankacc.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bankacc.Models.Transaction", b =>
                {
                    b.HasOne("bankacc.Models.Transaction")
                        .WithMany("alltransaction")
                        .HasForeignKey("TransactionId1");
                });
#pragma warning restore 612, 618
        }
    }
}
